### ISSUE TITLE
Undo no longer works in a simple case

### ISSUE THREAD

**Issue by EricGrange** [bonecode/BCEditor#10]
With a file opened (any content, with anything on the first line)
- click to place cursor at start of first line line
- type 'a'
- hit ctrl + z

'a' is removed but the cursor is in an incorrect position

Further manipulations easily lead to corrupted memory.

**Comment by NilsHoyer** [comment]
I agree with you: BCEditor is **FAR** away from being stable. If you tell me the problems, I do my best to solve it. Maybe my best is not good enough for you... in that case, I simply can't assist you - I'm sorry.

Nevertheless I tried to fix this bug.

**Comment by den-low** [comment]
The undo and redo is totally unstable. Most of undo/redo action perform with bugs((

**Comment by NilsHoyer** [comment]
Yes, I know. Currently I re-new it nearly completely. Until now, I was very tricky with a lot of crazy hacks... Please give me one or tow days.

I'm sorry... 😢

**Comment by NilsHoyer** [comment]
Sorry for delay ... I rebuild the entiered undo / redo feature and removed more than 1,000 lines code while doing this. I hope, now it works without many new problems... :wink:
