### ISSUE TITLE
Scrollbars

### ISSUE THREAD

**Issue by piker00** [bonecode/BCEditor#11]
![scroll](https://cloud.githubusercontent.com/assets/11677236/24569079/33119f50-166d-11e7-86c9-67dbd8bf29d2.gif)

**Comment by NilsHoyer** [comment]
Thank you for your video!

I removed the `Scroll.Bars` property and implemented `HideScrollbars` to be more compatible with `TRichEdit`. Additional, I've fixed the bug.
