### ISSUE TITLE
Bug in unit BCEditor.Editor;

### ISSUE THREAD

**Issue by piker00** [bonecode/BCEditor#12]
procedure RegExSearch(const APattern: string; const ABeginPosition, AEndPosition: TBCEditorTextPosition);   

Now:
{$if CompilerVersion > 26}
      Include(**F**Options, roNotEmpty);
      {$endif}

Must be:
{$if CompilerVersion > 26}
      Include(**L**Options, roNotEmpty);
      {$endif}

**Comment by NilsHoyer** [comment]
Thank you - I will enclose this change to the next commit.
