### ISSUE TITLE
Scroll\Word wrap\selection

### ISSUE THREAD

**Issue by piker00** [bonecode/BCEditor#13]
Single click selects text \ and lmb click + mouse move doesn't select text

![1](https://cloud.githubusercontent.com/assets/11677236/24590144/f17b0e52-17f0-11e7-8b62-3b52795fb0fb.gif)

Scroll not works\ Word wrap not works

![2](https://cloud.githubusercontent.com/assets/11677236/24590149/fc06cf32-17f0-11e7-9e59-949b1bfac3f3.gif)

**Comment by NilsHoyer** [comment]
I've fixed and commited both problems - thank you for your video!
