### ISSUE TITLE
Error installing into Delphi Berlin

### ISSUE THREAD

**Issue by DmLam** [bonecode/BCEditor#13]
Get error 

Unit '..\Source\BCEditor.Editor.CodeFolding.Ranges.pas' not found

when installed the package into Delphi 10.1
Commenting lines
`
BCEditor.Editor.CodeFolding.Ranges in '..\Source\BCEditor.Editor.CodeFolding.Ranges.pas',
BCEditor.Editor.CodeFolding.Regions in '..\Source\BCEditor.Editor.CodeFolding.Regions.pas',`

in BCEditor.Delphi.Berlin.dpk solved the problem

**Comment by NilsHoyer** [comment]
Thank you for you note - I've fixed this bug.
