### ISSUE TITLE
hints in 64 bit mode

### ISSUE THREAD

**Issue by ericlangedijk** [bonecode/BCEditor#14]
[dcc64 Hint] BCEditor.Editor.pas(10067): H2164 Variable 'LKeyword' is declared but never used in 'PaintLines'
[dcc64 Hint] BCEditor.Editor.pas(10068): H2164 Variable 'LLine' is declared but never used in 'PaintLines'

**Comment by NilsHoyer** [comment]
In line 10067 of `BCEditor.Editor.pas` is inside `PrepareTokenHelper` on my end - and I can't locate `LKeyword` inside this file.

Can you check, if you pulled my last update?

Currently, I'm using https://github.com/bonecode/BCEditor.git, but this should be redirected from https://github.com/bonecode/TBCEditor.git too.

**Comment by ericlangedijk** [comment]
I downloaded the last zip from https://github.com/bonecode/BCEditor.git.
Indeed 10067 is now inside PrepareTokenHelper so I have the latest version.
The old hints disappeared. Some new ones appeared :-)
Using Delphi 10.2 Tokyo.  The hints only appear when compiling in 64 bits mode...

[dcc64 Hint] BCEditor.Editor.pas(6438): H2164 Variable 'LChar' is declared but never used in 'TCustomBCEditor.InsertLineIntoRows'
[dcc64 Hint] BCEditor.Editor.pas(6440): H2164 Variable 'LFirstPartOfToken' is declared but never used in 'TCustomBCEditor.InsertLineIntoRows'
[dcc64 Hint] BCEditor.Editor.pas(6451): H2164 Variable 'LTokenLength' is declared but never used in 'TCustomBCEditor.InsertLineIntoRows'

**Comment by NilsHoyer** [comment]
I removed the unneeded declarations - thank you.

I'm using XE4 (and I don't want to update, to make sure, BCEditor works also for this "old" Delphi version.

But you are right: If I compile the `BCEditor.Package.Runtime` separately, I get this hints too - but I don't get them, if I compile a program, which uses this package. Maybe I have to compile the package everytime, before I commit an update - but that would be a lot of work... 😞

**Comment by ericlangedijk** [comment]
Maybe you can make a projectgroup with the package inside it and use "build all projects"?
I will keep track of this project sometimes. Great work!

**Comment by NilsHoyer** [comment]
Yes, I alread have a project group. Good idea for checking the hints. Maybe I remember this in the future not to bother you with this hints further more.

... but I still don't understand, why I don't see that hints, if I compile my "normal" program, which uses the `BCEditor.Editor.pas` file?

**Comment by ericlangedijk** [comment]
Wild guess: maybe because the program uses the package?
In that case try a program which does *not* use the package, but only the units.
Add the editor(s) @runtime in your test-program.
