### ISSUE TITLE
May be its better to make translation of ATSynEdit from lazarus to delphi ?

### ISSUE THREAD

**Issue by piker00** [bonecode/BCEditor#16]
Please take a look at
https://github.com/Alexey-T/ATSynEdit

it has all features of BCEditor and much more. May be it's better to drop BCEditor development and try to translate ATSynEdit to delphi ? what do you think ?

**Comment by NilsHoyer** [comment]
In the moment, I don't work on BCEditor. Maybe I do this again later on 
- maybe I take a look to that project. Thank you for your note.
