### ISSUE TITLE
C++ Builder 10.2 İnstall Problem

### ISSUE THREAD

**Issue by ademalp** [bonecode/BCEditor#17]
Packages are not installed. I think it needs to be renewed for new versions C++ Builder

**Comment by NilsHoyer** [comment]
Thank you for your note.

I'm not a C++Builder developer - are you able to solve this problem and 
tell me, what I have to change?

If you need my assistance ... can you describe the problem more detailed?

**Comment by oalex33** [comment]
Hello, Nils!
I can't install components in Delphi XE7.
When I try install package, I get a mistake -> 
BCEditor.Package.Runtime.dpk(76): F1026 File not found: '...\BCEditor-master\Packages\Win32\Debug\BCEditor.Editor.Minimap.dcu'

**Comment by NilsHoyer** [comment]
My mistake - and I've fixed this "Minimap" problem now.

Thank you for your note.

**Comment by oalex33** [comment]
Its Ok now!

Thanks.
