### ISSUE TITLE
Demo <> Demo screenshot

### ISSUE THREAD

**Issue by derChristoph** [bonecode/BCEditor#27]
My Demo looks like this:
![image](https://cloud.githubusercontent.com/assets/13977320/25839870/cc13c8f0-3499-11e7-8b7d-55bafa014439.png)

and i get an AV after klicking:
![image](https://cloud.githubusercontent.com/assets/13977320/25839891/e2f850ea-3499-11e7-86af-dcb97ca7f4fd.png)

**Comment by NilsHoyer** [comment]
I tried to fix this bug and I commited the fix.
