### ISSUE TITLE
Assertion failure in BCEditor.Lines.pas after click on empty editor

### ISSUE THREAD

**Issue by jaclas** [bonecode/BCEditor#28]
Put on form empty TBCEdit control. Compile and start application, and mouse click inside editor:

![vps_04](https://cloud.githubusercontent.com/assets/17312717/25846902/1225d184-34b4-11e7-88d9-e2703fa15a23.png)

**Comment by NilsHoyer** [comment]
This problem should be fixed. Thank you.
