### ISSUE TITLE
Assertion failure in BCEditor.Lines.pas after click on empty editor - still exist in other place

### ISSUE THREAD

**Issue by jaclas** [bonecode/BCEditor#29]
![vps_02](https://cloud.githubusercontent.com/assets/17312717/25948720/3028da1c-3655-11e7-9b28-290ec047e565.png)

**Comment by NilsHoyer** [comment]
I think, you are using EurekaLog. Do you have the call stack for this issue for me?

**Comment by jaclas** [comment]
Please:
[AccountsManager.zip](https://github.com/bonecode/BCEditor/files/992996/AccountsManager.zip)

**Comment by NilsHoyer** [comment]
This report shows a problem on a different position.

I've tried to solve both problems and I pushed the changes.

Please let me know, if you still have problems with it...

**Comment by jaclas** [comment]
Assert exception still exists:

[AccountsManager.zip](https://github.com/bonecode/BCEditor/files/993098/AccountsManager.zip)

**Comment by NilsHoyer** [comment]
Thank you for you patience with my and for your assistance.

Now I was able to reproduce this problem - and I've fixed and pushed the fix.

**Comment by jaclas** [comment]
Yes, now is ok, thx :-)
