### ISSUE TITLE
Descriptions...

### ISSUE THREAD

**Issue by jaclas** [bonecode/BCEditor#32]
Please add to commits some description. Even the simplest like: 
- refactoring
- new feature
- bug fix

etc.

Thanks :-)

**Comment by NilsHoyer** [comment]
For all commits: Cleanup, bug fixes - maybe removing a feature.

Currently, I don't plan any new feature.

**Comment by jaclas** [comment]
I know, I mean future commits :-)
When I pull new version I want to know if this is an important change.

**Comment by NilsHoyer** [comment]
If I think there is something important, I will communicate it. ;-)
