### ISSUE TITLE
Resize

### ISSUE THREAD

**Issue by Rjalarvo** [bonecode/BCEditor#34]
I get ERangeError exception of 'line x is not visible' when I execute fullscreen change by pressing F11. I have logging event on formkeydown that writes to the BCE. Line 6539.

Also typing into BCEditor while the FormKeyDown logger is active hangs the program. From PreviewKey := true

```
procedure TForm3.FormKeyDown(Sender: TObject; var Key: Word; Shift: TShiftState);
begin
  Log('Key pressed: '+Key.ToString);

  if Key = 122 then
    begin
      fullScreen := not FullScreen;
      SetFullScreen;
    end;
end;

procedure TForm3.SetFullScreen;
begin
  if FullScreen then
    begin
      BorderStyle := bsNone;
      WindowState := wsMaximized;
    end
  else
    begin
      BorderStyle := bsSizeable;
      WindowState := wsNormal;
    end;
end;

procedure TForm3.Log(const aString: string);
begin
  BCEditor1.Lines.Add(FormatDateTime('hh:mm:ss:zzz', now)+ ' ' +aString);
end;
```

**Comment by NilsHoyer** [comment]
I've found a problem with adding a line while on an empty text - and I've fixed it.

Can you test, if this solves this issue?

**Comment by Rjalarvo** [comment]
Tried to achieve the same with updated source at my work computer, and I couldn't.
