### ISSUE TITLE
Old interesting discussion

### ISSUE THREAD

**Issue by jaclas** [bonecode/BCEditor#35]
https://plus.google.com/105626236962310493174/posts/6JDepnpnxje

Maybe is worth to split BCEditor code to independent modules?

**Comment by NilsHoyer** [comment]
You want to work on the BCEditor project? What kind do you want to overtake?

**Comment by jaclas** [comment]
No, I'm not able to improve BCEditor, now my knowledge about this control is too weak. 
I pasted the link because it seems to worth considering this direction of develop.
