### ISSUE TITLE
Question: Release policy

### ISSUE THREAD

**Issue by acambule** [bonecode/BCEditor#36]
Hi there,

first thank you for sharing this nice Editor.

Reguarding the readme.html in my release, i use Version 1.7.0 of BCEditor.

The readme says:
<b>Note!</b> Current trunk should never be considered as a stable version. Use the latest <a href="https://github.com/bonecode/TBCEditor/releases">release</a> version instead. 

As there are no releases on that link, and other releases like the 1.7.0 can not be found anymore,
i would like to know if you may have a stable release, maybe with some bugfixes after V. 1.7.0
that could be used?

I've tried the current master-trunk, but it seems you are working on massive refactoring, the most public methods were changed to protected, so that it can not be considered to be used for now.

thanks and regards
Antonio Cambule

**Comment by NilsHoyer** [comment]
Please don't waste your and my time with this question. If you want to support this project, please use your time to show problems or improvements.
