### ISSUE TITLE
Background color not set

### ISSUE THREAD

**Issue by Private-Storm** [bonecode/BCEditor#38]
Maybe while not much info available but can it be that the background color is not set correctly?
See demo (btw. doesn't happen in the precompiled demo application)

![1](https://user-images.githubusercontent.com/1253735/28995372-ea2e2e8c-79e7-11e7-9107-c6d787bd18bd.PNG)

**Comment by Private-Storm** [comment]
Wie ich vermutet habe, der Editor färbt nur die Zeilen die Text enthalten ansonsten bleibt die Hintergrundfarbe auf weiss stehen. Was dem Monokai.json widerspricht wenn ich das richtig lese wird dort die Hintergrundfarbe des Editors gesetzt. Scheint also ignoriert zu werden.

**Comment by NilsHoyer** [comment]
In Monokai.json gibts diese Zeile:
```
        "Background": "$00222827",
```

Das ist die Hintergrundfarbe. In deinem Screenshot wird auch genau diese Farbe angezeigt - nicht schwarz. Aus meiner Sicht ist also alles gut...

**Comment by Private-Storm** [comment]
Da muss ich wiedersprechen, schau Dir den Screenshot nochmal an, woher kommt der weisse Hintergrund? Oder wir verstehen uns da falsch das weisse soll doch ebenfalls "Background": "$00222827", sein ist es aber nicht wie ersichtlich, sondern eben weiss. Heisst egal was man setzt das weisse da bleibt weiss

**Comment by NilsHoyer** [comment]
Den Fehler habe ich gefunden und für das nächte Update behoben. Danke für deine Geduld.

**Comment by Private-Storm** [comment]
Kein Thema, ich hätte das auch direkt erwähnen können, dass es nicht um den Texthintergrund geht.
