### ISSUE TITLE
Argument ausserhalb des gültigen Bereichs

### ISSUE THREAD

**Issue by Private-Storm** [bonecode/BCEditor#39]
Wenn man das Demo kompiliert, wird ja ein Beispiel Quelltext geladen, je nach ausgewähltem Highlighter.

Jetzt mal im Editor eine Zeile anklicken und dann return drücken:

Exception BCEditor.Editor Argument ausserhalb des gültigen Bereichs...
Funktion TCustomBCEditor.LinesToRows(const ALinesPosition: TBCEditorLinesPosition): TBCEditorRowsPosition;

Zeile: 5569

**Comment by NilsHoyer** [comment]
Das Problem hab ich behoben.
