### ISSUE TITLE
Asserts

### ISSUE THREAD

**Issue by tonyt73** [bonecode/BCEditor#4]
```
  if ((ALine = 0) and (Count = 0)) then
    Result := nil
  else
  begin
    Assert((0 <= ALine) and (ALine < Count));

    Result := @Lines[ALine].Attribute;
```

I feel the `if` should be the inverse of the `Assert(...)`
In this case:

```
if ((ALine <0) or (ALine >= Count)) then
```
This would stop so many of these asserts firing.

**Comment by NilsHoyer** [comment]
ALine should be a valid line number while using `Attribute`.

Inside `BCEditor.Lines.pas`, I cleaned up the code - in `BCEditor.Editor.pas` currently I'm working.

But until now, I didn't get a assertion failor. Do you get it with a special highlighter or do you get it always?

Btw:
Lasse developed the BCEditor and gave up this project. So now I work on it further more...

**Comment by tonyt73** [comment]
From within the demo; I got it when I changed to a new highlighter.
It was especially problematic when there when selecting a line greater than the file length.
It could be my compiler (RX Berlin); it has been doing strange things lately.

**Comment by NilsHoyer** [comment]
I'm sorry, it works fine for me to select a larger line.

But I will go ahead cleaning the code. Maybe I find the problem on this way...
