### ISSUE TITLE
Control 'BCEditor1' has no parent window.

### ISSUE THREAD

**Issue by civilian7** [bonecode/BCEditor#42]
When inserting the TBCEditor in design mode,
The following error message occurs :

"Control 'BCEditor1' has no parent window.

i'm using Tokyo 10.2.1

**Comment by AlbertWiersch** [comment]
I just ran into the same problem.

Is anyone support BCEditor anymore? It's a shame... and what happened to most of the source files? Looks like I'm going to have to dump BCEditor. :(

**Comment by NilsHoyer** [comment]
I've fixed this bug for the next commit.
