### ISSUE TITLE
Which license does BCEditor use?

### ISSUE THREAD

**Issue by mcdurdin** [bonecode/BCEditor#47]
I am interested in looking at using BCEditor as a replacement for an encumbered syntax highlighting editor for Keyman Developer (https://github.com/keymanapp/keyman). However, the licensing is unclear for BCEditor. Which license would you place BCEditor under (may I suggest MIT)?

https://help.github.com/articles/licensing-a-repository/ has great suggestions on license options.

**Comment by NilsHoyer** [comment]
I don't play the game of "Licenses".

**Comment by LeaVerou** [comment]
> I don't play the game of "Licenses".

Care to elaborate?

**Comment by cambell-prince** [comment]
https://help.github.com/articles/licensing-a-repository/ states that:

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

So although you don't want to play the game of licenses (which I agree can be sadly frustrating) the default position is that your project cannot be used legally by anyone at all.

**Comment by AlbertWiersch** [comment]
This should be made very clear... that there is no license to use or redistribute this software. I'm glad I saw this.

**Comment by NilsHoyer** [comment]
Decide this by yourself.
