### ISSUE TITLE
Visual Basic code folding has issues with nested "if"

### ISSUE THREAD

**Issue by brianjford** [bonecode/BCEditor#5]
When using the visual basic highlighter, if you have a nested IF, like:
if a = 5 then
  if b = 10 then
    do something
  end if
end if

It thinks the "end if" is actually the start of a new block (because it has an openToken contained within the CloseToken).

![nested_if](https://cloud.githubusercontent.com/assets/16192488/24336280/36974330-125a-11e7-8045-edfb0a880f3c.png)

**Comment by NilsHoyer** [comment]
I'm new on this project (I overtook it some weeks before). So I'm not sure, but I think and `OpenToken` cannot have multiple words.

But I wish to have this feature too (for the SQL highlighter), so I will check it soon. Maybe one or two weeks, I think...

**Comment by NilsHoyer** [comment]
Currently the scan for close tokens will be handled for complete words. So if you have `end if` inside the text, it compares `end` with the `CloseToken` of the hightlighter - and this doesn't match.

Or let me explain it on an other way: Currently word break characters are not allowed inside a `CloseToken` definition.

Indeed it would be nice to have a better detection of the code folding. But how much work is senseful on this? A really good code fodling (like know from the RAD Studio IDE) based on a logical analyzing of the semantic - not only of single words. And this can be done for every different language only. This can't be the sense of the BCEditor.

So a compromize would be to allow multple words for detection of begin and end line for the code folding. But handling this, the empty space between the words must be detect as well. Maybe you have two `<SPACE>` or a `<TAB>` between `END` and `IF` inside your text. You would be handled this too.

This is a lot of work and will slow down the scanning of the code folding ranges.

I don't believe I will do this in the near future - I'm sorry.
