### ISSUE TITLE
Topline property or Save/Restore editor state

### ISSUE THREAD

**Issue by Dimonka2** [bonecode/BCEditor#51]
Again about the topline property. It seems that you havent seen my comment.

>    TopLine, I removed complete. Why do you want to have it?

Basically I use one editor for several files and I need to restore the document state while switching between files. TopLine was a part of the "restoration". Maybe you can suggest a better way to persist editor state?

**Comment by NilsHoyer** [comment]
> It seems that you havent seen my comment.

I don't have an internet access at home. If I want to be online, I have 
to ride my bike for 8 km. I don't do that every day.

**Comment by NilsHoyer** [comment]
I've added TopLine again.
