### ISSUE TITLE
demo crashes on every click

### ISSUE THREAD

**Issue by jeancremers** [bonecode/BCEditor#52]
Every click on a language = read of addresss 00000008
Click on colors does not work first time.

**Comment by NilsHoyer** [comment]
I was not able to get this bug message. But I got an other one - and I fixed them.

Can you test it, and let me know, if the problem is gone on your end?

**Comment by NilsHoyer** [comment]
I tested this again with Delphi XE4 and 10.2. But I don't get a problem.

Unfortunately, I don't find the address. So I don't have an idea, how I can solve this problem...

**Comment by jeancremers** [comment]
Sorry i can't help you more. Succes!
