### ISSUE TITLE
Changes in code, lack of PixelsToTextPosition()

### ISSUE THREAD

**Issue by jaclas** [bonecode/BCEditor#53]
How to replace this code from old version BCEditor:

> procedure TfrmViewHTMLEditor.bcedtMarkdownDropFiles(ASender: TObject; APos: TPoint; AFiles: TStrings);
> var
>   lPosition: TBCEditorLinesPosition;
> begin
>   inherited;
>   lPosition := bcedtMarkdown.PixelsToTextPosition(APos.X, APos.Y);
>   bcedtMarkdown.CaretPos := Point(lPosition);
> 

Method PixelsToTextPosition() disappear from BCEditor code

**Comment by NilsHoyer** [comment]
BCEditor should support OLE Drop File without your work. If this would work, you would not need to handle it by yourself. But I never tested that.

Should I test that for you?

**Comment by jaclas** [comment]
How activate OLE Drag&Drop?

**Comment by NilsHoyer** [comment]
II should work with the derault Options (eoDropFiles).

Seems it does not work on your end. I will test this feature soon. Currently, I hunt your oder issue since 3 hours...

**Comment by NilsHoyer** [comment]
I've tested the drop of files into the BCEditor: There was an access 
violation inside. But now, it works for me.

**Comment by jaclas** [comment]
Drag&Drop work, but...

As I wrote before I need to handle dropped file and replace file body with short string. 
I don't want the content of the file to be inserted into the text
How handle drop and insert into editor my short string (and store in background original file contents to my internal structure)?

**Comment by NilsHoyer** [comment]
I believe your wish is your (private) wish only. Not a lot of users are interessted about this. Right?

If yes, what do you think about this:
You use TBCEditor.BeforeProcessCommand to capture `ecDropOLE` command.

With `PBCEditorCommandDataDropOLE(AData).Pos`, you can get the text position (Character and Line), where to insert your short string.

You can do this, with
```
SelStart := Lines.CharIndexOf(PBCEditorCommandDataDropOLE(AData).Pos);
SelLength := 0:
SelText := YourShortString;
```

With `AAllow := False`, BCEditor will not insert the content of the dropped file.

This solution is not easy, I agree with you. But if you are the only one, who wants to use it, I believe this could be Ok for you. Am I right?

(I should offer a manual about this, but I should do so many things and I don't have enough time to do all of them. Sorry.)

**Comment by jaclas** [comment]
Yes, it's my personal need. Not for implementation in the editor :-)
Thanks a lot for example.

Q: What is Lines.CharIndexOf? I did not find this method.

**Comment by jaclas** [comment]
Oh, CharIndexOf is protected...
But this is trivial and only first problem...
Next... after set SelStart TBCEditor call ProcessCommand (from OLE ProcessCommand) and there is trouble:
this assertion raises exception:
  Assert(not (ecProcessingCommand in FState));

**Comment by NilsHoyer** [comment]
Sorry, my mistake. Please use `TBCEditor.PosToCharIndex` to get the index for `SelStart`.

Yes, you are right: Currently, it's not possible to execute a command, while a command is beeing proceeded. But how can I solve this problem? Maybe, I have to implement a command queue. I believe, you will not be the only one, who want's to catch one command and replace it by an other one.

But maybe, somebody want's to execute two commands, while catching one. So I can't offer you to change the current command.

You could also use the Windows Message queue for this, but I don't believe this is a good solution.

Please give me one or two days to think about this issue, I try to find a solution for you.

**Comment by jaclas** [comment]
Maybe it would be enough to call the FBeforeProcessCommand() event before setting the fState to ecProcessingCommand?

**Comment by NilsHoyer** [comment]
I've implemented `PostCommand`. It works simmilar to ProcessCommand, but it will be executed after the current command processing. Maybe you can test this for me?

I'm not sure, if it's sensefull to have both: `ProcessCommand` and `PostCommand`. Maybe I will remove `PostCommand` later one. If this happens, `ProcessCommand` can be called everytime.

**Comment by jaclas** [comment]
Perhaps you should add this code at begin of ProcessCommand?

```
  if (ecProcessingCommand in FState)) then
  begin
    LCommand.Command := ACommand;
    LCommand.Data := AData;
    FCommands.Enqueue(LCommand);
    Exit;
 end;
```

**Comment by NilsHoyer** [comment]
I will not remove `PostCommand`. A calling to `ProcessCommand` gives back, if the command was handled, since it was processed allways.

`PostResult` gives back only, if the command was processed. So with `PostCommand, you don't know, if the command was handled. `PostCommand` can't return, if the command was handled, since maybe it was just added the the queue.

**Comment by NilsHoyer** [comment]
Yes, I tried this. But the `Result` is the problem. The `Result` of `ProcessCommand` tells, if it was handled. But this is not known, if it just was enqueued. So wether `True`, nor `False` would be valid.

I would implement a tri-state return value. This makes it not easier to implement `ProcessCommand`.

And inside the WinAPI, we have `SendMessage` and `PostMessage` as two different methods too.

**Comment by jaclas** [comment]
Did you try to move call FBeforeProcessCommand before set fState (Include(FState, ecProcessingCommand)) and FAfterProcessCommand after clear fState (Exclude(FState, ecProcessingCommand))?

**Comment by NilsHoyer** [comment]
I don't want this. I think the whole processing of a command should be protected as one block.

... but I believe, that would work fine...

**Comment by jaclas** [comment]
But how now use this solution?

**Comment by NilsHoyer** [comment]
Just use `PostCommand` inside your `BeforeProcessCommand` event. I believe, this should work fine. (I made a small test with replacing ecDown to ecUp - that worked for me.)

**Comment by jaclas** [comment]
This is complicated and unusable :(
I have no idea how to do the parameters for PostCommand.
...and If I need three changes in the editor:

     bcedtMarkdown.SelStart: = x
     bcedtMarkdown.SelLength: = 0;
     bcedtMarkdown.SelText: = 'xxxx';

then I have to send three separate PostCommand() and individual parameters? OMG...

**Comment by jaclas** [comment]
Can not it be made in the background, on the setter side of these properties when fState is ecProcessingCommand?

**Comment by jaclas** [comment]
Finally I did something like that, but it was a tiresome road... strange and unintuitive. In addition, the user must know the editor's internal types.

```
  lData : TBCEditorCommandData;
  lSel: TBCEditorLinesArea;


    lSel.BeginPosition.Char := lPoint.X;
    lSel.BeginPosition.Line := lPoint.Y;
    lSel.EndPosition := lSel.BeginPosition;
    lData := TBCEditorCommandDataSelection.Create(lSel, True);
    bcedtMarkdown.PostCommand(ecSel, lData);
    lData := TBCEditorCommandDataText.Create('test', False, False);
    bcedtMarkdown.PostCommand(ecText, lData);

```

**Comment by NilsHoyer** [comment]
Sorry, I didn't know, you get the same trouble with SelStart - I thought, you would call ProcessCommand.

Can we find a solution together?
If you would call `SelStart := ..` as usual and BCEditor add it to the queue for you, you would wonder, why reading `SelStart` shows the old value. This would happens, since the command was not proceeded immediately.

If I would follow your wish to move the `esProcessCommand` it would work for you, I think. But `BeforeProcessCommand` is not the only way to catch commands. You can also add a "hook" of the commands. For example, the macro recorder use it. So your wish whould work for you - but not for the hooks.

Maybe I should implent something like `BeginQueue` and `EndQueue`. So if you use that enclosing, you would be able to use `SelStart :=` ... and you would know, it's queued and not executed immediately.

... but this solution is not good too. But what could be a better one? If I would allow you to modify command inside the `BeforeProcessCommand` and inside the "hook",  the inner hooked routine would get an other command, that the user initiated. This is bad too.

In the moment, I don't have an idea. I hope I will get a good idea soon...

**Comment by NilsHoyer** [comment]
Btw: `SelLength := 0` is not needed. I checked `SelStart :=` - it's set the length to "0" always.

**Comment by jaclas** [comment]
Is this code correct?

```
  Exclude(FState, ecProcessingCommand);
  if (not (ecProcessingCommand in FState)
    and (FCommands.Count > 0)) then
  begin
    Include(FState, ecProcessingCommands);
    LCommand := FCommands.Dequeue();
    ProcessCommand(LCommand.Command, LCommand.Data);
    Exclude(FState, ecProcessingCommands);
  end;
```

You set ecProcessingCommands flag and call recursively ProcessCommand, but you don't check this flag.

Question 2: How get body of dropped file?

**Comment by NilsHoyer** [comment]
Indeed: No. I try to fix it now.

You can get the filename of the dropped file, like described in `DoDropOLE`. Than, you have to open that file by yourself. Maybe with `TFileStream`, like shown in `TBCEditorLines.InsertFile`. OLE Drop, reports only the filename - not the body of the file.

**Comment by jaclas** [comment]
Maybe it is worth adding public methods to extract the file name and content?
Like this:
function TCustomBCEditor.GetDroppedFileName(const AData: PBCEditorCommandDataDropOLE; out aFileName : string) : Boolean;
function TCustomBCEditor.GetDroppedFileBody(const AData: PBCEditorCommandDataDropOLE; const aStream : TStream) : Boolean;

**Comment by NilsHoyer** [comment]
Every additional method, makes it harder for new developers to implement BCEditor. I believe there are not a lot of developers, who wants to get the name or body of a dropped file. I'm sorry.

I tried to solve the problem with the state - and implemented a better message, if a command should be processed, while a command is being proceeded.

I'm sorry, but I don't have an internet access at home. Because of this, I need often many time to answer you. (Currently, I'm sitting a in public mall.)

**Comment by jaclas** [comment]
Why new methods is problem for new developer? Imho lack of method is problem because it limits capabilities. A new user don't need to use these methods. Btw these extra methods could be in a separate unit as a class helper.  In that case, you could also use the helpers. It would be clean and simple.

**Comment by jaclas** [comment]
Btw in this additional unit you could insert methods for PostCommand, for example:
procedure PostSelStart (aIndex: Integer);
procedure PostSelText (const aText: string);
etc.
and inside this method prepare and call PostCommand()

**Comment by NilsHoyer** [comment]
As more you have, as more problems you have to find what you are looking for.

I plan to offer BCEditor also as a DLL to implement it from other languages as only from Delphi. For that, I have to implement a small numbers of methods to makes it easier to implement the DLL. For that, maybe ProcessCommand / PostCommand will be available only as one Windows message.

In that case, you can use the Windows message EM_SETSEL with PostMessage. That should work for you right now today too. And with EM_REPLACESEL, you can insert a text.

**Comment by jaclas** [comment]
We probably did not understand. Class helper does not interfere with the code, is a separate entity. There is no impact on the DLL interface, it will only help for delphi developers.

**Comment by NilsHoyer** [comment]
I know Helpers in Delphi. But again: As more code I implement into BCEditor, it more time other people needs to find, what they are looking for. Additional,  need more time to manage the code and make sure, everything is always up to date.
