### ISSUE TITLE
Bugs when selecting and deleting text

### ISSUE THREAD

**Issue by yarekc** [bonecode/BCEditor#61]
I got alert messages such as

`Command not allowed . Use PostCommand(47..)`

It takes some time to happen: I need to select ALL, (ctrl+A) then delete DEL key

I also got sometimes: 

`Argument out of range`

Happens randomly after N CTRL+A, DEL

Any idea ?

**Comment by NilsHoyer** [comment]
I was able to reproduce this bug, after an exception occurred while processing a command. I've fixed this bug in the latest commit.
