### ISSUE TITLE
shift + backspace = ?

### ISSUE THREAD

**Issue by ValeriyTitov** [bonecode/BCEditor#64]
```
  BCEditor:=TBCEditor.Create(Self);
  BCEditor.Parent:=Self;
  BCEditor.Align:=alClient;

  BCEditor.Highlighter.LoadFromFile('E:\BCEditorSmall\Highlighters\SQL - Standard.json');
  BCEditor.Highlighter.Colors.LoadFromFile('E:\BCEditorSmall\Colors\Default.json');
```
![1](https://user-images.githubusercontent.com/34241725/43798137-52b7d176-9a92-11e8-85e1-57ff53e2fb42.png)

**Comment by NilsHoyer** [comment]
What should happens on <Shift+Backspace>?

**Comment by ValeriyTitov** [comment]
> What should happens on <Shift+Backspace>?

Nothing or as ussual withiout Shift

For now, strange symbols appearing after i press <Shift+Backspace>, as on screenshot.

**Comment by NilsHoyer** [comment]
I've fixed this issue. Thank you.
