### ISSUE TITLE
Most of highlighter Jsons are invalid

### ISSUE THREAD

**Issue by ValeriyTitov** [bonecode/BCEditor#69]
Most of highliter Json are invalid. 
I cannot load highlighters for Json, xml syntax and so on.
Symbols are missing in Json

> Error: Parse error on line 3:
> ...		"Name": "JSON"		"FileExtensions": [
> ---------------------^
> Expecting 'EOF', '}', ':', ',', ']', got 'STRING'

I checked those jsons on https://jsonlint.com

**Comment by NilsHoyer** [comment]
I've added the missing commas. Thank you for your note.
