### ISSUE TITLE
Add Hightlighter.LoadFromJson(const Json:string)

### ISSUE THREAD

**Issue by ValeriyTitov** [bonecode/BCEditor#70]
```
procedure TBCEditorHighlighterColors.LoadFromJson(const Json: string);
var
 Stream:TStringStream;
begin
 Stream:=TStringStream.Create;
  try
   Stream.WriteString(Json);
   Stream.Position:=0;
   LoadFromStream(Stream);
  finally
  Stream.Free;
 end;
end;
```
Same method goes to Hightiter and HighlighterColors.

Just another method to simplify load of syntax and colors. It's better to use it, when you dont want to keep external files with syntax.

**Comment by NilsHoyer** [comment]
Maybe I have to switch back to the external toolbox to load JSON data... :-(

**Comment by NilsHoyer** [comment]
Currently, there is a separation between colors and highlighter definition. I don't like this too, since I believe each highlighter needs a special colors file. But other people like this separation.

So maybe your request is only sense ful for you?

**Comment by ValeriyTitov** [comment]
Hi.
I was not talking about seperation. I like seperation idia.
This suggestion to load syntax/color from direct JSON strings.

I keep syntax in Memos as JSON text, instead of of files. 
```
 BCEditor.Highlighter.LoadFromJson(Memo1.Lines.Text);
 BCEditor.Highlighter.Colors.LoadFromJson(Memo2.Lines.Text);
```

**Comment by NilsHoyer** [comment]
Sorry, I misunderstood you. :(

Now I implemented your solution - without testing it. Can you test it and let me know, if it doesn't work?

**Comment by ValeriyTitov** [comment]
Yes. It worked.
With new warning.

> [dcc32 Warning] BCEditor.Consts.pas(28): W1061 Narrowing given WideChar constant (#$00B4) to AnsiChar lost information
