### ISSUE TITLE
Add Syntax property to BCEditor

### ISSUE THREAD

**Issue by ValeriyTitov** [bonecode/BCEditor#71]
Just a suggetion.
I rewrote a bit your code, and added Syntax property.
To autoamticly load syntax and it's colors to BCEditor.
Syntax can be easily switched by setting Syntax property

TSyntaxStorage.Add('Pascal', PascalSyntaxJson, PascalColorJson); //global class for all instances of BCEdit
TSyntaxStorage.Add('C#', CSharpSyntaxJson, VisualStudioColorJson); 

BCEditor.Syntax:='Pascal';
BCEditor.Syntax:='C#';

```
unit BCEditor.Editor;

interface

uses
  ...BCEditor.SyntaxStorage;

TBCEditor = class(TBCBaseEditor)
  strict private
     FSyntax:string;
     procedure SetSyntax(const Value: string); 
   protected
     procedure LoadSyntax(Syntax:TBCEditorSyntaxItem);
   public
    property Syntax:string read FSyntax write SetSyntax;
  end;


procedure TBCCustomEditor.LoadSyntax(Syntax: TBCEditorSyntaxItem);
begin
 Highlighter.LoadFromJson(Syntax.Syntax);
 Highlighter.Colors.LoadFromJson(Syntax.Color);
end;

procedure TBCCustomEditor.SetSyntax(const Value: string);
 if FSyntax<>Value then
  begin
    LoadSyntax(TBCEditorSyntaxStorage.GetSyntax(Value));
    FSyntax:=Value;
  end;
end;


______________________
unit BCEditor.SyntaxStorage;

TBCEditorSyntaxItem = class
  private
    FSyntax: string;
    FColor: string;
  public
    property Syntax:string read FSyntax write FSyntax;
    property Color:string read FColor write FColor;
    constructor Create(ASyntax, AColor:TMemo);
  end;

  TBCEditorSyntaxStorage = class
   public
    class function GetSyntax(const SyntaxName:string):TBCEditorSyntaxItem;
  end;

implementation

var
 FStorage:TObjectDictionary<string,TBCEditorSyntaxItem>;
 FForm: TBCSyntaxStorageForm;

constructor TBCEditorSyntaxItem.Create(ASyntax, AColor: TStrings);
begin
 FSyntax:=ASyntax.Text;
 FColor:=AColor.Text;
 end;

{ TBCEditorSyntaxStorage }

class function TBCEditorSyntaxStorage.GetSyntax(const SyntaxName: string): TBCEditorSyntaxItem;
begin
if FStorage.ContainsKey(SyntaxName) then
  Result:=FStorage[SyntaxName]
   else
  raise Exception.CreateFmt('Cannot find syntax "%s"',[SyntaxName]);
end;

initialization
 FStorage:=TObjectDictionary<string,TBCEditorSyntaxItem>.Create([doOwnsValues], TIStringComparer.Ordinal);

finalization
 FStorage.Free;

end.

**Comment by NilsHoyer** [comment]
Like mentioned in the other issue, I agree with you: Each syntax need one highlighter and one color file. It's hard to handle both of them separately. But the ideo of Lasse is a standalone text editor program. There it makes sense to have separately files - one color file for all highlighters. And if the user loads a text file, the application has to switch the highlighter only.

This concept makes sense, for a text editor program - but no sense for a application like a SQL front end project. There we need more colors specifications.

**Comment by ValeriyTitov** [comment]
Once again, i think you misunderstood me.
Syntax property do not override standart mechanics - you can load Syntax/Colors seperately whenever you want.

In my case, Syntax property is pair of user defined Syntax/Colors schema (or even not implemented 3rd part - rules of filling popup combobox)
Another name: SchemaName. 
Those schemas should be stored(registed) globally for all instances of BCEditor.
Best choise to register those schemas once application start.

```

TBCEditor = class
public
  class procedure TBCEditor.RegisterSyntax(const SyntaxName, SyntaxJson, ColorsJson:string);
  property Syntax:string; get; set;
end;
.....

procedure FormCreate(Sender:TObject)
begin
 TBCEditor.RegisterSyntax('SQL',Form2.SQLJsonMemo.Text, Form2.SQLColorJsonMemo.Text);
 TBCEditor.RegisterSyntax('Pascal',Form2.PascalJsonMemo.Text, Form2.PascalColorJson.Text);
end;

procedure Button2Click(Sender:TObject)
begin
 BCEditor:=TBCEditor.Create(Self);
 BCEditor.Syntax:='SQL';
 BCEditor2:=TBCEditor.Create(Self);
 BCEditor2.Syntax:='Pascal';
end;

```
