### ISSUE TITLE
Provide runtime demo example

### ISSUE THREAD

**Issue by ValeriyTitov** [bonecode/BCEditor#73]
You constantly change your project,
If you provide run-time demo with your project, it will be easier to preview your component.
Currently, you have only design-time demo. Which should be recompiled and re-integrated to IDE each time BCEditor changes.

```
  BCEditor:=TBCEditor.Create(Self);
  BCEditor.Parent:=Self;
  BCEditor.Align:=alClient;

  BCEditor.Highlighter.LoadFromFile('.\Highlighters\SQL - Standard.json');
  BCEditor.Highlighter.Colors.LoadFromFile('.\Colors\Default.json');
  BCEDitor.Lines.Text:= BCEditor.Highlighter.Sample
```

**Comment by NilsHoyer** [comment]
There is a runtime demo too - linked from the main page of the project, not enclosed in the repository.

When I overtook the BCEditor Project from the initial developer (Thanks to Lasse), I cleaned it up. I think now, I cleaned the most code, so I hope there will not a lot of further changes.

**Comment by NilsHoyer** [comment]
This should not a lot of work - just create a TBCEditor object, set the Parent property and it works, I think.

**Comment by ValeriyTitov** [comment]
Yes. But i should do each time i download new .zip
New users, what just want to take a look at BCEditor, should do the same thing.

**Comment by NilsHoyer** [comment]
But enclosing an .exe file to the repository makes it very big...

**Comment by ValeriyTitov** [comment]
I think you understood me wrong.
Your current project have design-time demo with .pas and .dpr with total size of 5kb
To run this demo, i need to install component to IDE
Each time you change source, i need to recompile and reinstall it to IDE.

If you make run-time demo, when compoents created manually runtime , installation is no longer needed.

**Comment by NilsHoyer** [comment]
Yes, I understood you wrongly.
