### ISSUE TITLE
What does it mean ? (Icon)

### ISSUE THREAD

**Issue by ValeriyTitov** [bonecode/BCEditor#74]
Couldnt find description for that.

![01](https://user-images.githubusercontent.com/34241725/44836023-7d9a1580-ac3e-11e8-8f44-34903a4696df.png)

**Comment by NilsHoyer** [comment]
It's a synchon edit start button like given in the Delphi IDE too. If you select a text and click on the button, BCEditor will detect all equal words. If you edit on of that word, all others will be changed too.
