### ISSUE TITLE
Major XE compatibility regressions

### ISSUE THREAD

**Issue by EricGrange** [bonecode/BCEditor#8]
Recent commits have broken Delphi XE support, mostly:

- references to UITypes rather than Controls or StdCtrls
- removal of RectHelper
- use of Pos rather than PosEx
- use of character helpers rather than TCharacter.Xxx methods
- use of ${endif} rather than {$ifend}
- etc.

**Comment by NilsHoyer** [comment]
> Recent commits have broken Delphi XE support, mostly:

I work with XE4 - and I think it's a good time to update from XE to Berlin 10.1. Why don't you update Delphi?

> references to UITypes rather than Controls or StdCtrls

I re-sorted the units in the `uses` sections. Now I use `Winapi`, `System` and than `Vcl`. Is this a problem for XE? Are there identifiers which are used in different units?

Additional, I removed the namespace from the units. So I changed `System.UITypes` to `UITypes`. Is this a problem?

> removal of RectHelper

I don't understand, what you mean with `RectHelper`? I can't find this identifier in the last update from Lasse or in my current update...

> use of Pos rather than PosEx

I can't find `PosEx`. Where did you found it?

> use of character helpers rather than TCharacter.Xxx methods

What do you mean with this? `TCharacter` is not used ... and I do not remember to change something here...

Maybe it's also a problem or re-ordering the unit identifiers or removing their namespaces? Are there unit, you are using in a different namespace than `Winapi`, `System` and `Vcl`?

>  use of ${endif} rather than {$ifend}

The only location of `{$ifend}` I find in the `JsonDataObjects` unit. But also in the last update of Lasse, there has been used in `BCEditor.JsonDataObjects`. (I've updated this unit from Andreas Hausladen...)

If I'm right, `{$ifend}` is used after `{$if ...}`. And `{$ENDIF}` is used after `{$IFDEF ...}`. So they are very different.

**Comment by EricGrange** [comment]
> Why don't you update Delphi?

Stability issues (internal compiler errors), lack of time to upgrade and general lack of new features that could make the migration time worth it.

XE code should compile in XE4, so there is no real advantage to not being XE compatible. The only compatibility issues are minor syntax changes, not capability ones.

> Now I use Winapi, System and than Vcl. Is this a problem for XE?

Yes, that is a problem as the renamed units do not exist in XE (and it's just a renaming issue, the functionality is there)

> I don't understand, what you mean with RectHelper?

It was part of the XE compatibility commit by Stefan Glienke (67d4a0e5db2678496ba0d917412573c7c07f608d) which you overwrote.

> I can't find PosEx. Where did you found it?

It is in StrUtils

> use of character helpers rather than TCharacter.Xxx methods
> What do you mean with this? TCharacter is not used ... 

I mean using "c.IsLower" rather than "TCharacter.IsLower(c)" for instance, the XE compatibility commit had all those fixed, now they're back to incompatible.

> The only location of {$ifend} I find in the JsonDataObjects unit.

There are two {$endif} in BCEditor.Editor.Base

> If I'm right, {$ifend} is used after {$if ...}. And {$ENDIF} is used after {$IFDEF ...}. So they are very different.

Embarcadero flip-flopped on that syntax actually, JSONDataObject has a bit of code at the beginning to workaround the issue.

**Comment by NilsHoyer** [comment]
You don't want to update your Delphi compiler, since this costs your time and energy - I understand this. But supporting older Delphi versions costs my time and energy - and I don't like this.

You don't like my changes, since they do not longer work with your older Delphi compiler - I understand this. But cleaning up the code, makes it easier for me to understand and handle it.

How should we handle this difference?

Lasses started the BCEditor for Delphi XE4 and he didn't want to support older Delphi versions. In this case, I agree with Lasse: It's wasting engergy to port a new project to older versions. I'm sorry...
