### ISSUE TITLE
the very first character of text is selected only in 64 bits mode

### ISSUE THREAD

**Issue by ericlangedijk** [bonecode/BCEditor#8]
When compiling with 64 bits (Delphi Berlin) the first blank line of the editor is blue instead of the default light yellow. Also the first character is always selected when there is no selection.

**Comment by NilsHoyer** [comment]
If I try to compile `BCEditor.Package` for 64 bits (Delphi XE4), I get this error:

E2202 Required package 'designide' not found

Any suggestion, how I can compile this package for 64 bit?

This are my settings while installing Delphi:

![unbenannt](https://cloud.githubusercontent.com/assets/1734822/24584736/1a9007ae-1777-11e7-9f58-9c8861a9458d.png)

I don't have this problem with 32 bit. But I received an equal description from a end-user of a ready compiled 32bit program, that he hat a blue background, if he click into the BCEditor....

**Comment by tonyt73** [comment]
You can't build 64 bit packages for Delphi or Builder as they are 32 bit applications.
You can only build the 64bit runtime packages.
So you need to create a 64bit runtime only package and remove the designide package.

**Comment by NilsHoyer** [comment]
I've splitted back the `BCEditor.Package` to `BCEditor.Package.Runtime` and `BCEditor.Package.Designtime`.

Than I created a new "VCL Forms Application", added the "Win64" target platform, placed a `TBCEditor` component on the form and then I tried to compile it with the result:

_ E1026 File not found 'Controls.res'_

This file is located on my system here:
C:\Program Files (x86)\Embarcadero\RAD Studio\11.0\lib\win64\release

Do you know, which setting I have to change, that RAD Studio find this file?

**Comment by ericlangedijk** [comment]
I never use designtime packages. I just compiled my program in 64 bits and saw the strange selection line (blue) and the very first character selected.
Although now I installed the latest Delphi 10.2 Tokyo and the problem disappeared!

**Comment by NilsHoyer** [comment]
If the problem disappeared, I know why it occurred and I know who I solved it.

Nevertheless thank you for showing me the problems with the runtime / designtime package with 64 bit.
