### ISSUE TITLE
BCEditor1.Minimap.Visible := True;  Argument out of Range

### ISSUE THREAD

**Issue by piker00** [bonecode/BCEditor#9]
BCEditor1.Minimap.Visible := True; 
Causes an error message: Argument out of Range

**Comment by NilsHoyer** [comment]
I've fixed this error - but I still don't see a minimap.

Did I demaged the Minimap completely?

What kind of sense have the Minimap?

**Comment by piker00** [comment]
You mean removing forever or temporarily ?

**Comment by NilsHoyer** [comment]
Imho, this feature makes only sense, if it's updated in a separated thread in the background. As far as I can see right now, this is nearly a complete new implementation.

So in the moment, I will just remove that feature. If I bring it back later on I don't know in the moment.
